# .bashrc
#*******************************
# ABOUT THIS FILE
#
# bashrc is read for interactive non-login shells; bash_profile sources it
#*******************************

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

set -o vi

. ~/.ssh/agent >/dev/null 2>&1

export HISTTIMEFORMAT='%Y-%m-%d %H:%M:%S - '
export HISTFILESIZE=100000
export HISTSIZE=100000
export HISTFILE=~/.bash_history
shopt -s histappend
shopt -s cmdhist
export VISUAL=~/bin/cvim
export EDITOR=~/bin/cvim

export LESSBINFMT='*d\%o'
export LESS=-eRM
export PAGER=less
export MANPAGER='less -isR'
export MANPATH=/usr/local/man:/usr/local/share/man:$MANPATH

# Try to sort correctly
export LANG=en_US.UTF-8
export LC_COLLATE=C

alias vim=~/bin/cvim 

# Sorting issues
alias ls='LC_ALL=C ls -AF --color=auto'
alias sort='LC_ALL=C sort'

# Spelling mistakes
alias les=less
alias gerp=grep

# better default
alias tmux='tmux -2 -u '

# Yay forests
alias ps='ps --forest -f -e '
alias pg='ps --forest -f -e | grep '

# Easier lsof
alias li='sudo lsof -i -Pnl | grep LIST '
alias lsof='sudo lsof -i -Pnl '

# Color for grep
export GREP_OPTIONS='--color=auto'

export PATH="/home/rlpowell/bin:/root/bin:/usr/local/bin/:/usr/local/sbin:/opt/ruby/bin:/sbin:/bin:/usr/sbin:/usr/bin:$HOME/.rvm/bin:$PATH"

export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
