# .bash_profile
#*******************************
# ABOUT THIS FILE
#
# bash_profile *ONLY* is read for *login* shells, which is why we
# just source bashrc; we don't care about login vs. non-login as
# long as both are interactive
#*******************************

if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
