export HOST=$(uname -n)
export HOSTNAME=$HOST
export USER=$(id -un)
export USERNAME=$USER
export ARCH=$(uname -r)
export LANG=en_US.UTF-8
export VISUAL=cvim
export EDITOR=cvim

export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:$HOME/bin:$HOME/.rvm/bin

unset RUBYOPT

#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/environments/default"  # This loads RVM into a shell session.

if [ -e ~/.zshenv_local ]
then
	. ~/.zshenv_local
fi
