












#*******************************
# YOU ARE PROBABLY IN THE WRONG PLACE.  Try .bothrc
#*******************************














#*******************************
# ABOUT THIS FILE
#
# zshrc is read for interactive shells
#*******************************
#
# Generic .zshrc file for zsh 2.5
#
# .zshrc is sourced in interactive shells.  It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.
#

# vi key bindings
bindkey -v

# Do lots of magic completion crap
autoload -Uz compinit
compinit

# remove bindings defined in _history_complete_word in
# /usr/share/zsh or similar
bindkey -r '\e/'
bindkey -r '\e,'

# search path for the cd command
cdpath=(. .. ~ ~/src)

# Put information into the tmux title
function precmd { printf "\033]2;$(uname -n | cut -d . -f 1):$(echo $PWD | sed 's;/home/[^/]*powell;~;g')\033\\" }




# Color for grep
export GREP_OPTIONS='--color=auto'

# bigger shell functions to autoload
autoload zed
autoload run-help

# filename completion suffixes to ignore
#fignore=(.o .c~ .old)

# hosts to use for completion
#hosts=($HOSTANME mobius07.math.uwaterloo.ca calum.csclub.uwaterloo.ca)

# set prompts
USER=$(whoami)
HOSTNAME=$(uname -n | sed 's/\..*//')
export PS1="$USER@$HOSTNAME> "
#PROMPT='%m%# '    # default prompt
#RPROMPT=' %~'     # prompt for right side of screen

MAILCHECK=300
DIRSTACKSIZE=30

# set/unset  shell options
setopt   notify globdots correct pushdtohome cdablevars autolist
setopt   sunkeyboardhack autocd recexact longlistjobs
setopt   autoresume pushdsilent noclobber
setopt   autopushd pushdminus extendedglob rcquotes mailwarning
setopt   automenu sunkeyboardhack RM_STAR_WAIT
setopt   notify
# Stop things from acting differently than sh in an important way
setopt   sh_word_split

# This is not on by default, I just want to be clear
unsetopt correctall

# History settings
setopt INC_APPEND_HISTORY APPEND_HISTORY EXTENDED_HISTORY HIST_FIND_NO_DUPS HIST_EXPIRE_DUPS_FIRST
# Amount of history to save
export SAVEHIST=1000000
# Amount of history to load on start; fzf should ignore this
export HISTSIZE=10000
export HISTFILE=$HOME/.history_zsh

unsetopt rmstarsilent
unsetopt bgnice
unsetopt EXTENDED_GLOB 

# use hard limits, except for a smaller stack and no core dumps
unlimit
#limit stack 8192
#limit core 0
limit -s

export FZF_DEFAULT_OPTS='--extended'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# We use ctrl-t already
# From "/home/rlpowell/.fzf/shell/key-bindings.zsh"
zle     -N   fzf-file-widget
bindkey '\et' fzf-file-widget

if [ -e ~/.zshrc_local ]
then
	. ~/.zshrc_local
fi

if [ -e ~/.bothrc ]
then
	. ~/.bothrc
fi
