#!/bin/sh

# I think the idea here was that I could have this script be called
# "vim", and this path avoided loops.  Not really relevant anymore.
# export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:$HOME/bin:$PATH

clear && vim "$@"
