#!/bin/bash

# This is an external diff command for git.  Per
# https://web.archive.org/web/20170508180316/http://git.net:80/ml/version-control.msysgit/2008-06/msg00200.html
# , diff is called by git with 7 parameters:
#
# path old-file old-hex old-mode new-file new-hex new-mode

wdiff -n $2 $5 | colordiff --difftype=wdiff | (grep --color=never -C 5 '[{[][+-]' ; true)
