#!/bin/bash

# Runs ts, but the first column is delta in seconds from the
# previous line, second is datestamp, third is seconds since epoch.

lasttime=$(date +%s)
cat - | ts '%s' | while read line
do
  time=$(echo $line | awk '{ print $1}')
  deltaraw=$[ $time - $lasttime ]
  delta="$(printf '%3d' $deltaraw)"
  lasttime=$time
  nicedate="$(date -d @$time +%Y.%m.%d-%H:%M:%S)"
  echo "$delta $nicedate $line"
done
