#!/bin/sh -e

sep="$1"

rm -f /tmp/rlp_tmux_buf
tmux save-buffer /tmp/rlp_tmux_buf
if [ "$sep" ]
then
  cat /tmp/rlp_tmux_buf | sed 's/^ *//' | tr '\012' "$sep" >/tmp/rlp_tmux_buf.tmp
else
  cat /tmp/rlp_tmux_buf  | sed 's/^ *//' | tr -d '\012' >/tmp/rlp_tmux_buf.tmp
fi

tmux load-buffer -b ws_trim_wrap /tmp/rlp_tmux_buf.tmp
tmux paste-buffer -p -b ws_trim_wrap
rm /tmp/rlp_tmux_buf /tmp/rlp_tmux_buf.tmp
